### PR TITLE
MAX_RAW_SIZE limit for bodyParse.raw

### LINKED ISSUE #245: node12: add limit environment variable for raw (application/octet-stream)
I can't seem to set the limit for bodyParser.raw - i.e. when using a Content-Type: application/octet-stream

## Expected Behaviour
i was expecting an equivalent to the MAX_JSON_SIZE environment variable. 
I'm not a (js) programmer, but I couldn't find a clean way to set the limit for the raw parser.

## Current Behaviour
bodyParser.raw defaults to 100kb

## Possible Solution
I hacked the node12 template locally and simply added a MAX_RAW_SIZE, but there's probably a cleaner way.
```
    var jsonLimit = process.env.MAX_JSON_SIZE || '100kb' //body-parser default
    var rawLimit = process.env.MAX_RAW_SIZE || '100kb' //body-parser default
    app.use(bodyParser.json({ limit: jsonLimit}));
    app.use(bodyParser.raw({ limit: rawLimit})); // "Content-Type: application/octet-stream"
    app.use(bodyParser.text({ type : "text/*" }));
```

a generic MAX_SIZE might be cleaner though.

### PR DESCRIPTION
**Pull request by fundef1**
moved rawLimit out of if clause , so it can be applied to RAW_BODY as well. Is more consistent this way.

## Motivation and Context
cfr. https://github.com/openfaas/templates/issues/245

## Which issue(s) this PR fixes 

Fixes #245 

## How Has This Been Tested?
manually ;-)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Version change (see: Impact to existing users)

## Impact to existing users
none,

## Checklist:
- [x ] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Thanks for your interest in the project, please can you run the command that Derek has provided?

**Review by alexellis — CHANGES_REQUESTED** [review]
Please sign-off the commit as per the comment from Derek. Note this is not GPG signing, the command is provided.

**Comment by fundef1** [comment]
I'll try again over the weekend. 
The command provided by derek doesn't work (as I don't have a local copy - cfr webui).

**Comment by alexellis** [comment]
I'm not sure I understand the comment about Derek.

Are you saying you don't have a terminal and git available? 

@Waterdrips could you take over this PR please? It seems like it would be useful for the community.

**Comment by fundef1** [comment]
sorry didn't get around to this. 

But yes, to answer your question about derek: I edited the documentation directly on github.com without cloning/forking/... For a quick copy/paste like that it's the path of least resistance.... until derek. 

I understand the need for your hefty CONTRIBUTING.md ... but it is a little bureaucratic for a two-line edit ;-/
(when you are just playing around that is, I guess if you have everything set up already it's smooth as butter)

**Comment by alexellis** [comment]
Here is the absolute minimum required for every contribution:

https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md#sign-your-work

> But yes, to answer your question about derek: I edited the documentation directly on github.com without cloning/forking/... For a quick copy/paste like that it's the path of least resistance.... until derek.

This actually creates a fork automatically ☝️ 

You can also sign-off that commit in the UI, just read the section in the contributing guide on how.

Here's an example of something you can copy/paste into the UI:

```
Add alexellis to the .DEREK.yml file

We need to add alexellis to the .DEREK.yml file for project maintainer
duties.

Signed-off-by: Alex Ellis <alex@openfaas.com>
```

My concern with the approach of directly editing code in the UI is that it's hard to verify changes don't have syntax errors.

If using git to make code changes feels too beaucratic or too heavy-weight, that's OK. We can take this one on as it seems like it will benefit a broader audience.

I've pinged @Waterdrips to help.

**Pull request closed without merging**
