### PR TITLE
Add Swift Template

### PR DESCRIPTION
**Pull request by affix**
Add a Swift template to the template store

## Description
As requested by a few users and discussion with @alexellis I am submitting this swift language template to the openfaas template store.

## Motivation and Context
Requested by a few community members

## Which issue(s) this PR fixes 

Fixes #

## How Has This Been Tested?
Running on my personal cluster

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @affix this looks good to me.

Now here's how we get it into the function store:

* Create your own repo and move the files from this PR there
* Send a PR to https://github.com/openfaas/store/blob/master/templates.json
* I'll merge the PR and we'll be set

I'd also like to see swift-http for a non-forking version of the template. That can be done after if you like?

Alex

**Comment by alexellis** [comment]
All templates should also have a mechanism of adding packages or libraries. Is there one for Swift that you can add?

Alex

**Comment by affix** [comment]
yeah @alexellis there should be a way for it

**Comment by alexellis** [comment]
What about this?

https://github.com/apple/swift-package-manager

**Comment by alexellis** [comment]
[Dependencies are specified in your Package.swift manifest file.](https://github.com/apple/swift-package-manager/tree/master/Documentation)

**Pull request closed without merging**
