### PR TITLE
Stop using --no-cache with apk del

### LINKED ISSUE #78: Stop using --no-cache with apk del
## Expected Behaviour
We should not be using `--no-cache` with `apk del`.

## Current Behaviour
Most alpine based template `Dockerfile`s have `--no-cache` set which results in the APK index being downloaded when set (you can see this occur by setting the --verbose flag).
```
# apk del nginx -v --no-cache
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
...
```

## Possible Solution

Update `Dockerfiles`.

## Steps to Reproduce (for bugs)

1. `apk add curl --no-cache`
2. `apk del curl --no-cache --verbose`

## Context

Observed during review of php7 template.

## Your Environment
Alpine

### PR DESCRIPTION
**Pull request by johnmccabe**
## Description
Updates alpine based template `Dockerfile`s to not use `--no-cache`with `apk del` which is redundant and results in the APK index being downloaded when set (you can see this occur by setting the --verbose flag).
```
# apk del nginx -v --no-cache
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
...
```

## Motivation and Context

- [x] I have raised an issue to propose this change (#78)

## Which issue(s) this PR fixes 

Fixes #78 

## How Has This Been Tested?

Test locally with updated templates and observation of `faas build` output.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
I think this was added to prevent the errors like "package index not found".

**Comment by johnmccabe** [comment]
I'll try to reproduce that error, assume its where you've deleted the caches prior to attempt a package delete.

**Comment by ivanayov** [comment]
Should be hard to reproduce. It's fetching packages from `dl-cdn.alpinelinux.org/alpine`

P.S. I reproduced fetching without the `--no-cache` flag
```
 # apk del curl 
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
OK: 5 MiB in 14 packages
```

**Comment by ivanayov** [comment]
Reproduced only once, so it should not be an issue.

```
# apk del curl --no-cache
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/4) Purging curl (7.61.1-r0)
(2/4) Purging libcurl (7.61.1-r0)
(3/4) Purging nghttp2-libs (1.32.0-r0)
(4/4) Purging libssh2 (1.8.0-r3)
Executing busybox-1.28.4-r0.trigger
OK: 5 MiB in 14 packages

# apk del curl 
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
OK: 5 MiB in 14 packages

# apk del curl 
OK: 5 MiB in 14 packages

# apk del curl 
OK: 5 MiB in 14 packages

# apk del curl 
OK: 5 MiB in 14 packages

# apk del curl --no-cache
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
OK: 5 MiB in 14 packages

# apk del curl 
OK: 5 MiB in 14 packages

# apk del curl 
OK: 5 MiB in 14 packages
```

**Comment by alexellis** [comment]
@ivanayov what is your suggestion?

**Comment by alexellis** [comment]
Where are we on this?

**Comment by alexellis** [comment]
Sorry this PR has become inactive, I'm going to close. Feel free to raise a new one if required

**Pull request closed without merging**
