### PR TITLE
bump ruby version in template dockerfile

### PR DESCRIPTION
**Pull request by themoah**
bumping ruby & alpine version in dockerfile

## Description
ruby 2.7 was released recently
alpine 3.7 reached its EOL.

## How Has This Been Tested?
manually build (before and after the change).
`docker run -p 8080:8080 ruby-template:0.1` 
and then
`curl localhost:8080`
which returned
`Hello world from the Ruby template` (as expected)
docker log:
```
2020/01/05 13:33:25 Forking fprocess.
2020/01/05 13:33:25 Wrote 35 Bytes - Duration: 0.072239 seconds
```
## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Version change (see: Impact to existing users)

## Impact to existing users

newer version with backward compatibility.
## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Thanks for the PR, can you send one over to https://github.com/openfaas-incubator/ruby-http too?

Are there breaking changes involved in moving from Ruby 2.5 to 2.7? cc @kaihoffman @andyjeffries

**Comment by kaihoffman** [comment]
Hi @alexellis 2.7 implements all methods etc from previous versions, it simply adds new features. 3.0 next year will be the one with potential breaking issues.

**Comment by themoah** [comment]
@alexellis it's only security fixes and some major GC improvement (alongside JIT). All new features will be released with 3.0.

**Comment by alexellis** [comment]
Let's go for it then.

**Pull request merged**
