### PR TITLE
Shifts watchdog download to dotnet-runtime

### LINKED ISSUE #73: Install curl what already exists
## Expected Behaviour
The Dockerfile in the csharp template contains only required steps.

## Current Behaviour
The Dockerfile install curl to download the watchdog. After that curl will be uninstalled. There is no need for this steps. The program curl is already part on the image microsoft/dotnet:2.1-runtime.

### Console output of my test
root@vmd24929:~# docker run -it --rm microsoft/dotnet:2.1-runtime /bin/bash
root@40ce644ee8a3:/# apt-get install curl ca-certificates
Reading package lists... Done
Building dependency tree
Reading state information... Done
curl is already the newest version (7.52.1-5+deb9u7).
ca-certificates is already the newest version (20161130+nmu1+deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

## Possible Solution
Remove the steps in the dockerfile.

### PR DESCRIPTION
**Pull request by thomasjpfan**
Signed-off-by: Thomas Fan <thomasjpfan@gmail.com>

Moves the watchdog download to the dotnet-runtime.

## Description
Refactors the Dockerfile 

## Motivation and Context
Resolves an issue.

## Which issue(s) this PR fixes 

Fixes #73

## How Has This Been Tested?
`./verify.sh` passes with this refactor.

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by thomasjpfan** [comment]
The only issue this resolves is saving space/bandwidth from not having to download the `alpine:3.8` image.

This is similar to how https://github.com/openfaas/templates/blob/master/template/java8/Dockerfile does not use alpine to download watchdog.

**Comment by alexellis** [comment]
Derek add label: invalid

**Comment by alexellis** [comment]
I deliberately added this change so don't want to revert it. Please always comment on an issue before going ahead and raising a PR. This will save everyone time and make sure you're going to be most effective.

**Comment by alexellis** [comment]
My commit also addressed #73 so I've closed it now. We may move all templates to download the watchdog in this way in the future for maintainability.

**Comment by thomasjpfan** [comment]
The workflow that is preferred seems to be:

1. If it is a new bug/feature, raise an issue to see if it is relevant.
2. If there is already an issue raised, comment to see if it is still relevant.
3. If one of the maintainers agree that it is an issue, now a PR can be submitted.

Is this workflow correct?

**Comment by johnmccabe** [comment]
That workflow looks about right @thomasjpfan.

When raising an issue that you'd also like to work on you can express that intent in comment at the time of raising.

**Comment by alexellis** [comment]
Just refer to the contributing guide, this is why it exists and we ask everyone to read it  before submitting PRs (it's part of the PR template even) -> https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md

**Comment by alexellis** [comment]
Derek lock

**Pull request closed without merging**
