### PR TITLE
Stop python precompiles

### PR DESCRIPTION
**Pull request by wbsp**
## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Which issue(s) this PR fixes 

Fixes #

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by wbsp** [comment]
oops -- sorry. wrong repo.

**Comment by alexellis** [comment]
@wbsp I'm really concerned that you have forked OpenFaaS copyrighted code and given it the copyright of Oath Inc without any attribution. This isn't valid usage within the license terms.

Have you rebranded OpenFaaS as `Verizon Media Platform: Edge Functions`?

**Comment by wbsp** [comment]
apologies -- wasn't paying attention -- meant to push this PR to a fork we are working on. 

As for the copyright -- apologies. I will straighten that out now. there are some slight modifications we introduced to the templates for a system we were experimenting with. I

**Comment by alexellis** [comment]
I'm concerned about infringement of Copyright and license.

From looking at the commit, it looks like you have rebranded OpenFaaS as `Verizon Media Platform: Edge Functions`. Is that correct?

I'd be curious to know more about how you are using OpenFaaS. Please can you have your people reach out to alex@openfaas.com ?

**Comment by wbsp** [comment]
to close the loop here -- rebranding was not our intent. Apologies for the clumsy work there. We have corrected the license file after our discussion. Thanks for your understanding!

**Pull request closed without merging**
