### PR TITLE
Use of-watchdog 0.9.3 to suppress custom health check logging messages

### LINKED ISSUE #283: Update of-watchdog version to 0.9.3
Update watchdog version to 0.9.3
## Expected Behaviour

Update watchdog version to 0.9.3
## Current Behaviour

Watchdog version is 0.9.2
## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

### PR DESCRIPTION
**Pull request by nitishkumar71**
Signed-off-by: Nitishkumar Singh <nitishkumarsingh71@gmail.com>

of-watchdog version to 0.9.3
## Description

of-watchdog version to 0.9.3
## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Which issue(s) this PR fixes 

Fixes #283

## How Has This Been Tested?

1. Made changes into template
2. Created new function with from local templates using `faas-cli new java11-test --lang java11 -f <path of template>`
3. Build function `faas-cli build -f ./java11-test.yml`
4. Deploy function `faas-cli deploy -f ./java11-test.yml`
5. Invoke function
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Version change (see: Impact to existing users)

## Impact to existing users

There should be no impact. As only kube-probe log is disabled
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by alexellis — APPROVED** [review]
LGTM

**Comment by alexellis** [comment]
/set title: Use of-watchdog 0.9.3 to suppress custom health check logging messages

**Comment by alexellis** [comment]
@nitishkumar71 I had feedback from a few users that they like to know _why_ something was changed not just how it was changed. What do you think of the new title?

**Comment by nitishkumar71** [comment]
> @nitishkumar71 I had feedback from a few users that they like to know _why_ something was changed not just how it was changed. What do you think of the new title? 

Make sense, will take care of this in future

**Pull request merged**
