### PR TITLE
Name of rootProject to be "java12" for Java12-template

### PR DESCRIPTION
**Pull request by SchulteMarkus**

### CODE REVIEW

**Comment by SchulteMarkus** [comment]
Closed as PR starved.

**Comment by alexellis** [comment]
Hi @SchulteMarkus the PR was not starved, you just didn't seem to take note of what Derek said to you.

The commits need to be signed-off, yours were not. You also need to fill out the PR template properly, again an automated bot told you that.

Contributions are welcome, but we need people to read the contribution guide and to follow it.

Alex

**Comment by alexellis** [comment]
In the meantime it seems like we did away with a Java12 template.

**Pull request closed without merging**
