### PR TITLE
Maven project of "model" to create as dependency repository in maven central

### PR DESCRIPTION
**Pull request by kameshchauhan**
A maven project was created to build as a java template dependency for function. The artifact will be published to maven central

## Motivation and Context
The issue is described in : https://github.com/openfaas/store/issues/70

## Which issue(s) this PR fixes 
This PR is one of the part of: https://github.com/openfaas/store/issues/70

## How Has This Been Tested?
The project was created from existing gradle project from /template/java

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by devongleeson** [comment]
I'm not sure I understand why this needed to go into a new directory? I think the publishing can happen out of the existing source tree. Also, it seems like the publishing should use gradle, even if your future projects will consume the interfaces using maven.

https://docs.gradle.org/current/userguide/publishing_maven.html

**Comment by alexellis** [comment]
I agree I would prefer this to use Gradle and be done outside of this template folder. Each user / function will get a copy of all of this data so we should move it up one level, or even out of the repository.

**Comment by kameshchauhan** [comment]
The idea is as below:
1. From the existing /templates/template/java8- the projects of model and entrypoint would be removed/moved to a level up at /templates/dependencies/*. So the developer when creating function using faas-cli --lang java will receive only the "function" project similar to other language template 
2. This existing projects of model and entrypoint can be kept as gradle project for publishing but were converted to maven based simply because it is more consistent and have first class support with Maven Central. Maven Central also support publishing of gradle based projects but has additional step to convert it to maven pom (though auto matically). 
3. Similar to gradle java template, i have created new maven based template at /templates/template/java8-maven. (in my private repo and PR pending)
4. The existing java8 template based on gradle will be updated to get model and entrypoint dependencies from Maven Central

**Comment by alexellis** [comment]
Sorry this PR is not signed-off and has become inactive, I'm going to close.

Feel free to raise a new PR.

**Comment by kameshchauhan** [comment]
Closing this PR means you don't want to add this feature in OpenFaaS. I had followed-up so many times to approve the PR when it was signed off but it seems this had no priority or requirement.

**Pull request closed without merging**
