### PR TITLE
Maven based java template for writing OpenFaaS function

### PR DESCRIPTION
**Pull request by kameshchauhan**
Use of Maven based build to create function in java

## Description
A new java template created which uses Maven as the build system.

## Motivation and Context
Currently the java template allows creation of java function that uses gradle as the only build system. There are many projects/developers/org. that would like to use Maven as the build system. So, in order to provide the flexibility a new template is created which additionally provides better developer experience in terms of dependency management, local project build etc...

## Which issue(s) this PR fixes 
Fixes # https://github.com/openfaas/store/issues/70

## How Has This Been Tested?
Tested on local machine providing dependencies by manual copy until those are available on Maven Central

## Types of changes
Added new project template that uses Maven POM build definition

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @kameshchauhan 

Please could you squash all your commits then sign-off again?

Alex

**Comment by wwelles** [comment]
@kameshchauhan I'm looking for something similar, any chance you could do what @alexellis was mentioning so this can be merged?

**Comment by kameshchauhan** [comment]
@wwelles Yes will do ASAP. Give me few days.

**Comment by wwelles** [comment]
@kameshchauhan thank you very much

**Comment by wwelles** [comment]
@kameshchauhan *ping*

**Comment by kameshchauhan** [comment]
@wwelles Sorry that it is taking some time. As you can see the PR was open since long and now and I have to merge on latest and retest it! Have been very busy with Istio stuff!

**Comment by wjljack** [comment]
when could merge it?

**Comment by kameshchauhan** [comment]
It has been ready since long to be merged. It depends on @alexellis

**Comment by alexellis** [comment]
Sorry this PR is not signed-off and has become inactive, I'm going to close.

Feel free to raise a new PR.

**Comment by senfo** [comment]
I'm confused about what's going on here. This would be a very useful PR and it seems like there's support from everybody involved, but there hasn't been an official signoff. Is this something you're willing to do, @kameshchauhan? Maybe you have somewhere else and I've simply overlooked it?

**Comment by kameshchauhan** [comment]
I can again prepare a PR if owner is commits to merge this time. It has been taking a very long in making final decision.

**Comment by senfo** [comment]
@kameshchauhan I'm coming in as an outsider. It looks like what happened was happening was you would sign up and then make updates, which also needed to be signed off. I definitely get the impression there was a lack of communication.

**Pull request closed without merging**
