### PR TITLE
Updated watchdog version

### PR DESCRIPTION
**Pull request by kwojcicki**
Signed-off-by: Krystian Wojcicki <kwojcicki@sympatico.ca>

## Description
Updated the classic-watchdog to the latest version and updated Dockerfiles to add watchdog all in the same format. Verified by building functions locally + verify.sh

## Motivation and Context
Now we can use the newer watchdog features such as max_inflight :D 

## Which issue(s) this PR fixes 

Fixes #

## How Has This Been Tested?
Verified by building functions locally + verify.sh

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Please can you confirm that you tested the java change that you made?

**Comment by alexellis** [comment]
Subject to testing from yourself this PR looks good to go.

**Comment by kwojcicki** [comment]
@alexellis  yup I tested all the none arm changes using ```verify.sh``` and any dockerfiles that I modified more than just the version I also tested by manually deploying :)

**Comment by kwojcicki** [comment]
ah crap fixing the merge conflict using githubs online editor was a mistake. Once I get home will fix the DCO.

**Comment by alexellis** [comment]
Don't worry.

I've taken the version bumps through, but not the other changes.

Please can you raise a new PR when you get home and include your other changes?

- CONTRIBUTING.md note on verify.sh
- the changing out of `curl` to get the watchdog for the multi-stage approach (not needed in the java* templates now)

**Pull request closed without merging**
