### PR TITLE
Csharp armhf template

### PR DESCRIPTION
**Pull request by zeerorg**
# Adds c# armhf template

## Description
Added a csharp-armhf template based on the previous csharp template. This is almost exactly similar to the previous csharp template, the only changes are in the template.yml language and adding fwatchdog-armhf instead of fwatchdog to the first docker builder.

## Motivation and Context
Dotnet core added support for ARM32 see [this link](https://github.com/dotnet/announcements/issues/29). This PR adds a template with arm support for csharp language.

## How Has This Been Tested?
Tested on own raspberry pi running raspbian with openfaas deployed on docker swarm.
Testing steps:

- Cloned the template to raspberry pi.
- Created new function with `faas-cli new --lang csharp-armhf temp`
- Build and deploy function with `faas-cli build -f temp.yml && faas-cli deploy -f temp.yml`
- Invoke function from Openfaas ui.

This doesn't affect other templates.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hey @zeerorg thank you for this! Are you in the #arm-and-pi Slack channel?

Alex

**Comment by zeerorg** [comment]
Yes

**Comment by alexellis** [comment]
Hi @zeerorg 

There was a report on Slack of this template not working and failing to load the function.

Could you look into it please?

Alex

**Comment by alexellis** [comment]
When I updated to 2.2 I got this error:

```
curl -d test http://127.0.0.1:8080/function/ctest
exit status 136
Failed to load ?B?, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/home/app/libcoreclr.so'
```

```
FROM alpine:3.8 as watchdog

RUN apk --no-cache add curl \
    && echo "Pulling watchdog binary from Github." \
    && curl -sSL https://github.com/openfaas/faas/releases/download/0.13.0/fwatchdog-armhf > /usr/bin/fwatchdog \
    && chmod +x /usr/bin/fwatchdog \
    && cp /usr/bin/fwatchdog /home/app \
    && apk del curl --no-cache

FROM mcr.microsoft.com/dotnet/core/sdk:2.2.203-stretch-arm32v7 as builder

# Supress collection of data.
ENV DOTNET_CLI_TELEMETRY_OPTOUT 1

# Optimize for Docker builder caching by adding projects first.

RUN mkdir -p /home/app/src/function
WORKDIR /home/app/src/function
COPY ./function/Function.csproj  .

WORKDIR /home/app/src/
COPY ./root.csproj  .
RUN dotnet restore ./root.csproj

COPY .  .

RUN dotnet publish -c release -o published -r linux-arm

FROM mcr.microsoft.com/dotnet/core/runtime:2.2.4-stretch-slim-arm32v7

COPY --from=watchdog /usr/bin/fwatchdog  /usr/bin/

# Create a non-root user
RUN addgroup --system app \
    && adduser --system --ingroup app app

WORKDIR /home/app/
COPY --from=builder /home/app/src/published .
RUN chown app:app -R /home/app

USER app

ENV fprocess="dotnet ./root.dll"
EXPOSE 8080

HEALTHCHECK --interval=3s CMD [ -e /tmp/.lock ] || exit 1

CMD ["fwatchdog"]
```

**Pull request merged**
