### PR TITLE
Update the java8 template to honor cgroups memory limits

### LINKED ISSUE #129: Java8 template does not honor container memory limits
The JVM prior to 8u131 did not support cgroup memory limits ([reference](https://bugs.openjdk.java.net/browse/JDK-8170888)). This means that the JVM can overrun the memory allocated to it by its container, causing the container to be OOMKilled.

A better description of the issue (and resolution) can be found in this presentation entitled [Why you’re going to FAIL running Java on docker!](https://docs.google.com/presentation/d/1cdfrMCG_BEYL7wka11Ovw0GPUelrlB91XmaKx2WaQUg/edit#slide=id.g1e56d4b0f2_0_1)

## Expected Behaviour

Invoking the sample function defined below should result in a 200 OK response with the body containing something like `Allocated more than 80% (75.5 MiB) of the max allowed JVM memory size (89.0 MiB)` without the container crashing.

## Current Behaviour

When the function is invoked, its container crashes and a 500 Internal Error Response is returned.

## Possible Solution

Upgrade openjdk to at least 8u131 and use the `-XX:+UnlockExperimentalVMOptions` and  `-XX:+UseCGroupMemoryLimitForHeap` arguments to the java command.

## Steps to Reproduce (for bugs)

1. Create a new function using the java8 template
2. Use the code at the end of this issue as the implementation
3. Apply memory limits as described below
4. Invoke the function via curl
5. Observe a 500 response

## Context

I came across this issue when building another JVM-based template and thought it would be good to share. :)

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
Docker CE 18.09.1

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
FaaS-netes

* Operating System and version (e.g. Linux, Windows, MacOS):
macOS Mojave 10.14.3

* Link to your project or a code example to reproduce issue:

Use the following implementation for a java8-based function. This is based on the [Java Docker Fail](https://github.com/burrsutter/javadockerfail/blob/master/boot-boom/src/main/java/com/burrsutter/bootboom/MyController.java) sample.

```java
public static String humanReadableByteCount(long bytes, boolean si) {
    int unit = si ? 1000 : 1024;
    if (bytes < unit)
        return bytes + " B";
    int exp = (int) (Math.log(bytes) / Math.log(unit));
    String pre = (si ? "kMGTPE" : "KMGTPE").charAt(exp - 1) + (si ? "" : "i");
    return String.format("%.1f %sB", bytes / Math.pow(unit, exp), pre);
}

private String bigString() {
    System.out.println("Starting to allocate memory...");
    Runtime rt = Runtime.getRuntime();
    StringBuilder sb = new StringBuilder();
    long maxMemory = rt.maxMemory();
    long usedMemory = 0;
    while (((float) usedMemory / maxMemory) < 0.80) {
        sb.append(System.nanoTime() + sb.toString());
        usedMemory = rt.totalMemory();
    }
    String msg = "Allocated more than 80% (" + humanReadableByteCount(usedMemory, false) + ") of the max allowed JVM memory size ("
            + humanReadableByteCount(maxMemory, false) + ")";
    System.out.println(msg);
    return msg;
}

public IResponse Handle(IRequest req) {
    Response res = new Response();
    res.setBody(bigString());

    return res;
}
```

You will also need to apply constraints to the function, e.g.:

```yaml
limits:
  memory: "200Mi"
requests:
  memory: "100Mi"
```

### PR DESCRIPTION
**Pull request by tessellator**
This commit upgrades the openjdk version to the earliest that supports
cgroup memory limits. It also applies the JVM arguments required to
enable the support.

This change is needed for the JVM to recognize the actual memory
made available to it via the container instead of believing it has
access to the amount of memory possessed by the node running the
container.

Signed-off-by: Chad Taylor <taylor.thomas.c@gmail.com>

## Description

This PR updates the java8 template to use a newer version of the OpenJDK that supports cgroup memory limits. It also updates the JVM to use the flags necessary to enable the cgroup memory limits support in production.

## Motivation and Context

- [X] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md)) 

## Which issue(s) this PR fixes 

Fixes #129

## How Has This Been Tested?

Using this template and the function defined in #129, I was able to successfully invoke the function without crashing the container and receiving a 200 OK response with `Allocated more than 80% (75.5 MiB) of the max allowed JVM memory size (89.0 MiB)%` in the body.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
SGTM

**Comment by alexellis** [comment]
Is there anything else we need to do around Java? I'd like your help to review #86

**Comment by tessellator** [comment]
I'll take a look this morning.

**Comment by alexellis** [comment]
👍

**Pull request merged**
