### PR TITLE
Add source compatibility flags

### PR DESCRIPTION
**Pull request by devongleeson**
## Description
Pin the source compatibility and target compatibility to java 1.8
because that is the intended runtime. This work is part of #137.

I added the flags to the subprojects block, and the function
build.gradle explicitly. The reason for the extra block in the function
is because developers of java functions mainly only be working with this
build.gradle, and the rest of the gradle is under the covers during the
function build process that the faas-cli provides.

## Motivation and Context
When doing local development, I found it possible to accidentally be compiling code at java 11 rather than 1.8 source compatibility, this caused problems while I was working through building my function.

- [X] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Which issue(s) this PR fixes 
This addresses part of #137

## How Has This Been Tested?
I built the jar locally, and then ran it inside the 1.8 container and it worked correctly.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by devongleeson** [comment]
I use intellij, so I added the intellij file *.iml to the gitignore so I don't accidentally commit those files.

**Comment by devongleeson** [comment]
@alexellis I'm wondering if this is considered good enough to merge? Who should I be pinging for feedback on my PRs?

**Comment by alexellis** [comment]
The only thing I'd ask you to do @devongleeson is to squash your commits and rebase.

I can't merge right now due to this error: `This branch cannot be rebased safely`

Please make sure you have no merge commits in your PR, and feel free to create a new PR if that's easier for you.

**Comment by alexellis** [comment]
Sorry to bring this up again, but there is a new rebase conflict. This time on `.gitignore` which was edited by another contributor

**Comment by alexellis** [comment]
Note that I don't get pings if you re-push your code after a rebase, so it looks like I was still waiting to hear from you were last here in April.

Are you able to take a look this weekend so we can get it closed out?

**Comment by ieugen** [comment]
@devongleeson : Do you have time to squash, rebase and fix the conflict for this PR so it gets merged? 
If not, please say so others could step in (if that is ok with you).

**Pull request closed without merging**
