### PR TITLE
Allow vendor dir in golang's function folder

### PR DESCRIPTION
**Pull request by diddledan**
The go templates check for formatting, but exclude vendored files in the template folder itself ignoring any additional vendor folder in the function folder.
---
- Add extra eclusion for function/vendor folder when checking file formatting

Fixes OpenFaas/templates#1

### CODE REVIEW

**Comment by alexellis** [comment]
Thank you for the PR. This is because certain vendored deps don't conform to gofmt right?

**Comment by diddledan** [comment]
That's correct. It is a scratch-my-own-itch because I couldn't get a build to work at all without vendoring, and once I'd added the vendor libraries I received build failures from gofmt:

```plain
Step 5/17 : RUN test -z "$(gofmt -l $(find . -type f -name '*.go' -not -path "./vendor/*"))" || { echo "Run \"gofmt -s -w\" on your Golang code"; exit 1; }
 ---> Running in 42657253d697
./function/vendor/golang.org/x/net/ipv6/batch.go:56:14: expected type, found '='
./function/vendor/golang.org/x/net/ipv6/batch.go:69:2: expected declaration, found 'if'
./function/vendor/golang.org/x/net/context/go19.go:15:14: expected type, found '='
./function/vendor/golang.org/x/net/context/go19.go:20:17: expected type, found '='
./function/vendor/golang.org/x/net/ipv4/batch.go:59:14: expected type, found '='
./function/vendor/golang.org/x/net/ipv4/batch.go:78:2: expected declaration, found 'if'
./function/vendor/golang.org/x/image/draw/go1_9.go:41:13: expected type, found '='
./function/vendor/golang.org/x/image/draw/go1_9.go:44:12: expected type, found '='
./function/vendor/golang.org/x/image/draw/go1_9.go:47:9: expected type, found '='
./function/vendor/golang.org/x/image/draw/go1_9.go:57:16: expected type, found '='
./function/vendor/golang.org/x/text/message/catalog/go19.go:13:14: expected type, found '='
./function/vendor/golang.org/x/text/message/catalog/go19.go:15:22: expected type, found '='
Run "gofmt -s -w" on your Golang code
The command '/bin/sh -c test -z "$(gofmt -l $(find . -type f -name '*.go' -not -path "./vendor/*"))" || { echo "Run \"gofmt -s -w\" on your Golang code"; exit 1; }' returned a non-zero code: 1
2017/12/21 00:16:33 ERROR - Could not execute command: [docker build -t diddledan/primitive .]
```

With this patch to the Dockerfile my builds succeed.

**Comment by alexellis** [comment]
I'm seeing a CI failure attached to the commit?

**Comment by diddledan** [comment]
No idea what the error is, but it seems to be using a different Dockerfile than the one in my commit to test against. As my commit is changing the Dockerfile this obviously means it's not testing my fix at all:

```
The command '/bin/sh -c test -z "$(gofmt -l $(find . -type f -name '*.go' -not -path "./vendor/*"))" || { echo "Run \"gofmt -s -w\" on your Golang code"; exit 1; }' returned a non-zero code: 1
```

This command is the reason for my fix which adds extra flags onto the `find`, which Travis seems to have ignored. My fix includes the following (note that the command executed by travis is not the command in my fix):

```Dockerfile
RUN test -z "$(gofmt -l $(find . -type f -name '*.go' -not -path "./vendor/*" -not -path "./function/vendor/*"))" || { echo "Run \"gofmt -s -w\" on your Golang code"; exit 1; }
```

**Pull request merged**
