### PR TITLE
Provide a PHP 8 template

### LINKED ISSUE #293: Template for PHP 8.1 (as 7.4 end of life will be 28 Nov 2022)
Since PHP 7.4's active support ended 28 Nov 2021 and security fixes will only be applied until 28 Nov 2022 it would be nice to have a php 8.1 template.

## Expected Behaviour
There is a PHP 8.1 template available

## Current Behaviour
There is only a PHP 7.4 template available.

## Are you a GitHub Sponsor (Yes/No?)
I bought the faasd eBook

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## List All Possible Solutions and Workarounds
There's no real "workaround" here.

## Which Solution Do You Recommend?
Deprecate the PHP 7 template, as official support for this version will end 28 Nov 2022, see https://www.php.net/supported-versions.php for reference.
Provide a PHP 8.1 template

## Context
I'm trying to build functions with the most recent PHP version, as it is relevant for frameworks like Symfony to use a modern and supported PHP version.

### PR DESCRIPTION
**Pull request by meacu1pa**
## Description
I added a new subfolder in the `template` directory, containing a PHP 8 template, including the `:latest` Composer image.
Further I had to remove the Phalcon example on installing extensions, because Phalcon right now has no PHP 8 support. It's being worked on, but I don't know when it will be available, so I removed it. The example is still available in the PHP 7 template.

## Motivation and Context
As described in #293 , PHP 7's end of life is near, so there is a need for a fresh PHP 8 template. The old template was also locked to an old version of Composer, hence I updated the Dockerfile to always use the latest version of Composer (v2). Also updated classic-watchdog version.

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Which issue(s) this PR fixes 
Fixes #293.

## How Has This Been Tested?
I verified that the build including the extensions example works, and did some simple tests by deploying the resulting image to a VPS running `faasd`. Also ran `./verify.sh`, worked.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Version change (see: Impact to existing users)

## Impact to existing users

Existing users will have the chance to create a template using PHP 8, the old PHP 7 template is still available. The `php7` template should be removed as soon as PHP 7 reaches end-of-.life (28 Nov 2022). Until then it might be nice to have a fallback solution.

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Thanks for this PR. 

Is Phalcon required or do you think that you could create a new example for us for this template?

**Comment by meacu1pa** [comment]
Personally I've never used Phalcon. If I were to enable extensions, I would do it the "Docker way", which is already shown in the example.

I spend some time looking for other interesting extensions that would require more work to get it working. Thought of Sentry or Blackfire.

Could try adding one of them, but imho it's not necessary.

**Comment by alexellis** [comment]
@rgee0 could you give this a run-through with a PHP example on your own cluster?

**Comment by kevin-lindsay-1** [comment]
I have tested this, was able to make a function that has src that differs from the template.

Made it alter the message via `return $data . '!!!!!!';`

**Comment by meacu1pa** [comment]
> I have tested this, was able to make a function that has src that differs from the template.
> 
> Made it alter the message via `return $data . '!!!!!!';`

From my side it's also good to go.

Let me know if anything is blocking the merge or needs to be changed @alexellis 

Cheers 🍻

**Review by alexellis — APPROVED** [review]
Approved

**Pull request merged**
