### PR TITLE
Update to latest .Net Core runtime

### PR DESCRIPTION
**Pull request by secana**
## Description
Updated the .Net Core template to the latest runtime and sdk version.

## Motivation and Context
All new .Net Core project created are automatically created with the new version 2.1 meaning that no new .Net Core project runs in the current template.

Furthermore the new version brings significant performance improvements at build and runtime.

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?
Build the new image to check if everything works as expected. 
Ran the image and check that the needed files are there.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @secana that sounds like a good move. Thanks for proposing the change.

Let me ping one or two people about this to make sure we are not introducing any breaking changes.

We can make this change in the project, or use your pull request, but you will need to sign off the commit. Signing-off is described in the contribution guide linked to by Derek.

Let me know if you'd like to join the [Slack community too](https://docs.openfaas.com/community/).

Alex

@BurtonR @rorpage

**Comment by alexellis** [comment]
@secana I also want to connect you with @BurtonR who has been working on a Kestrel template for a much higher throughput..

https://github.com/BurtonR/csharp-kestrel-template

The other .NET expert is @fpommerening 😄

**Comment by BurtonR** [comment]
There were *no* breaking changes in the .NET Core 2.1 release, so this should be a safe upgrade.
They did add some performance improvements which are always a good thing! 
[Here is the announcement post from Microsoft](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-2-1)

@secana once you `--amend` your commit with a sign-off I think we're good to upgrade!
Verified this with my C# functions locally. :+1:

**Comment by alexellis** [comment]
@rorpage did you test this change?

**Comment by alexellis** [comment]
@secana can you please see the comments? We are thankful for your change but need you to follow the process for contributions. If we don’t hear by the end of the week we’ll close this PR and re-do the work, so it would be great if you could follow-up.

Alex

**Comment by alexellis** [comment]
@secana it's been around 6 weeks since this PR was raised without completing a "DCO" sign-off. I think we can assume someone in the community needs to take over the work now so I'll close the PR and raise an issue for it.

If you decide to revisit the contribution guide and follow the above please just re-open the PR.

**Pull request closed without merging**
