### PR TITLE
Add table with templates in the repo

### LINKED ISSUE #100: Table of contents listing templates
Let's create a table of contents listing the template in this repo

| Name  | Language  | Version  | Linux base                 | Watchdog       | Link     |
|--------|-----------|---------|----------------------|--------------|--------|
| `python3` | Python | 3.6 | Alpine Linux 3.8 | Classic |                      | [template/python3](https://github.com/openfaas/templates/tree/master/template/python3) |

### PR DESCRIPTION
**Pull request by martindekov**
Adding table with the templates in the repository which
describes in general the templates along with reference
to the docs

Signed-off-by: Martin Dekov (VMware) <mdekov@vmware.com>

Added a table which contains general information for the templates in the repository

## Description

Adding table with template name, language, version of the language, linux base and link to the template in the repository, also added sentence for the docs

> Note: Some places I marked with N/A since was unable to find information in Dockerhub for the linux base and version of the language in that image

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Which issue(s) this PR fixes 

Fixes #100 

## How Has This Been Tested?

N.A. documentation adding

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by martindekov** [comment]
Hey @burtonr thanks for the review! I will amend the fixes, what about the `arm64v8/node:8.9.1`? Should I write debian ?

**Comment by burtonr** [comment]
I think it would be best to put `arm64v8/node:8.9.1` as that's the _real_ base image. I'll leave it up to you if you think that debian should be added perhaps in parentheses: `arm64v8/node:8.9.1(Debian)`

I think either would be fine.

**Comment by martindekov** [comment]
Thank you again for the suggestion @burtonr I will probably go with `Debian Linux` instead of the image base since It will be aligned with how the `Linux base` column looks (`Alpine Linux 3.8`)

**Comment by alexellis** [comment]
Thanks for this!

**Comment by alexellis** [comment]
Just one change needed. java8 does not use the "classic" watchdog.

**Pull request merged**
